### ISSUE TITLE
ImportError: cannot import name '_check_sample_weight'

### ISSUE THREAD

**Issue by idrismunir15** [tslearn-team/tslearn#275]
**Describe the bug**
The line of code below failed due to an import error : _cannot import _check_sample_weight_ . I really do not know what the issue is.

**To Reproduce**
from tslearn.clustering import TimeSeriesKMeans

**Environment (please complete the following information):**
 - OS: Windows/ Jupyter Notebook
 - tslearn version [e.g. 0.4.1]

**Comment by rtavenar** [comment]
Hi @idrismunir15 

Could you please provide the full error trace so that we can maybe identify the bug more easily? Did you install tslearn from `pip install tslearn`, via conda, or using the latest github-hosted version?

**Comment by GillesVandewiele** [comment]
Indeed :+1:, this seems to be related to sklearn... Perhaps it is not installed correctly?

**Comment by idrismunir15** [comment]
Sorry for late reply. I installed via pip install tslearn.

**Comment by idrismunir15** [comment]
> Hi @idrismunir15
> 
> Could you please provide the full error trace so that we can maybe identify the bug more easily? Did you install tslearn from `pip install tslearn`, via conda, or using the latest github-hosted version?

**---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-31-4b44bcc145ee> in <module>
----> 1 from tslearn.clustering import TimeSeriesKMeans

c:\python\lib\site-packages\tslearn\clustering.py in <module>
     18 from sklearn.utils import check_random_state
     19 from sklearn.utils.extmath import stable_cumsum
---> 20 from sklearn.utils.validation import _check_sample_weight
     21 from scipy.spatial.distance import cdist
     22 import numpy

ImportError: cannot import name '_check_sample_weight'

**Comment by rtavenar** [comment]
OK, then I guess maybe you have an "old" version of scikit-learn.
Can you try `pip install -U scikit-learn" ?

**Comment by idrismunir15** [comment]
I upgraded my scikit-learn library and it now it works. Thank you

**Comment by piyushy1** [comment]
> OK, then I guess maybe you have an "old" version of scikit-learn.
> Can you try `pip install -U scikit-learn" ?
This worked for me.

**Comment by crsilvac** [comment]
I have the same message. Which version of scikit-learn is expected?

**Comment by crsilvac** [comment]
![image](https://user-images.githubusercontent.com/48848848/94399304-77265100-01aa-11eb-9b30-2064fce5923a.png)

**Comment by GillesVandewiele** [comment]
Starting from [sklearn v0.22](https://github.com/scikit-learn/scikit-learn/blob/0.22.X/sklearn/utils/validation.py), `_check_sample_weight` is included. I would recommend upgrading scikit-learn to the latest stable version.

**Comment by crsilvac** [comment]
Ok, thank you. It works with **sklearn** v0.23.2
